name: Build
on: [push, pull_request]
jobs:
    build-firmware:
      runs-on: ubuntu-22.04
      env: 
        OUTPUT_DIR: ${{github.workspace}}/binaries
      steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update --assume-yes
          sudo apt install gperf python3-brotli mtools

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.x'

      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '14.2.Rel1'     

      - name: Install OpenWatcom 2.0
        uses: open-watcom/setup-watcom@v0
        with:
          version: "2.0-64"
          tag: "2024-03-01-Build"

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Build Firmware
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          mkdir -p $OUTPUT_DIR
          cmake $GITHUB_WORKSPACE/ -DWATCOM_PATH="$WATCOM"
          cmake --build . --parallel $(nproc)
          cp picopocket-sw.uf2 $OUTPUT_DIR/picopocket-sw.uf2

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: PicoGUS Firmwares
          path: ${{env.OUTPUT_DIR}}/picopocket-sw.uf2

